name: mph-table-50
URL: https://github.com/indeedeng/mph-table.git
checkoutID: dbd5413df33bf8f0a995822eeefe94df50f3c5a7
patchName: artifacts/configs/mph-table-50/mph-table-50.patch
mainJar: mph-table-1.0.6-SNAPSHOT-jar-with-dependencies.jar
testJar: mph-table-1.0.6-SNAPSHOT-tests.jar
#mvnOptions: -Dmaven.surefire.debug="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000"
properties:
  - name: TestSmartListSerializer#canRoundTripSerializableLists
    entryPoint: "com.indeed.mph.serializers.TestSmartListSerializer.canRoundTripSerializableLists(Ljava/util/List;Ljava/util/List;Ljava/util/List;)V"
