---
# Build & Install:
repository-url: "git@github.com:wcygan/java-callgraph-driver.git"
build-system: "maven"
build-command: "mvn install"

# Required Java-Callgraph options:
target-jar-location: "/target/java-callgraph-driver-1.0-SNAPSHOT.jar"

# Optional Java-Callgraph options:
# (Feel free to comment these out)
coverage-location: "/target/site/jacoco/jacoco.xml"
entrypoint: "\"edu.uic.cs398.Main.main([Ljava/lang/String;)V\""
depth: "5"
output-name: "example"
ancestry: "2"